试解内核编译错error:invalid lvalue ... 'm';"m"(func01)改为"i"(func01),但例子编译正常而链接报错；
试解内核编译错error:invalid lvalue ... 'm';"m"(func01)改为"i"(func01),但例子编译正常而链接报错；

"i"(func01) ： 例子 编译正常 但链接为可执行程序则报错； 内核刚开始的编译正常 不确定链接是否正常（还没到链接 ）；

"m"(func01) ：例子 编译正常 且 链接正常； 内核编译报错 kernel/bounds.c:22:142: error: invalid lvalue in asm input for constraint 'm'


kernel/bounds.c:22:142: error: invalid lvalue in asm input for constraint 'm'
__asm__  __volatile__ (   "jmp 0f \n\t"    "or $0xFFFFFFFF,%%edi \n\t"    "orL $258,%%edi \n\t"    "orL %0,%%edi \n\t"    "0: \n\t" : : "m"( &main ) ); /*filePath=kernel/bounds.c,line=17,column=1,abs_location_id=258,funcName=main,srcFileId=1*/


//////kernel/bounds.c  内容如下
#pragma message("funcId_asm_inserted")
// SPDX-License-Identifier: GPL-2.0
/*
 * Generate definitions needed by the preprocessor.
 * This code generates raw asm output which is post-processed
 * to extract and format the required data.
 */

#define __GENERATING_BOUNDS_H
/* Include headers that define the enum constants of interest */
#include <linux/page-flags.h>
#include <linux/mmzone.h>
#include <linux/kbuild.h>
#include <linux/log2.h>
#include <linux/spinlock_types.h>

int main(void)
{__asm__  __volatile__ (   "jmp 0f \n\t"    "or $0xFFFFFFFF,%%edi \n\t"    "orL $258,%%edi \n\t"    "orL %0,%%edi \n\t"    "0: \n\t" : : "m"( main ) ); /*filePath=kernel/bounds.c,line=17,column=1,abs_location_id=258,funcName=main,srcFileId=1*/
	/* The enum constants to put into include/generated/bounds.h */
	DEFINE(NR_PAGEFLAGS, __NR_PAGEFLAGS);
	DEFINE(MAX_NR_ZONES, __MAX_NR_ZONES);
#ifdef CONFIG_SMP
	DEFINE(NR_CPUS_BITS, ilog2(CONFIG_NR_CPUS));
#endif
	DEFINE(SPINLOCK_SIZE, sizeof(spinlock_t));
	/* End of constants */

	return 0;
}
///////// 编译命令如下:

/app/llvm_release_home/clang+llvm-15.0.0-x86_64-linux-gnu-rhel-8.4/bin/clang -Wp,-MD,kernel/.bounds.s.d -nostdinc -isystem /app/llvm_release_home/clang+llvm-15.0.0-x86_64-linux-gnu-rhel-8.4/lib/clang/15.0.0/include -I./arch/x86/include -I./arch/x86/include/generated -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -Qunused-arguments -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -no-integrated-as -Werror=unknown-warning-option -fno-PIE -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fcf-protection=none -m32 -msoft-float -mregparm=3 -freg-struct-return -fno-pic -mstack-alignment=4 -march=i686 -mtune=generic -Wa,-mtune=generic32 -ffreestanding -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mretpoline-external-thunk -fno-delete-null-pointer-checks -Wno-frame-address -Wno-int-in-bool-context -Wno-address-of-packed-member -O1 --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=1024 -fno-stack-protector -Wno-format-invalid-specifier -Wno-gnu -Wno-tautological-compare -mno-global-merge -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -Wdeclaration-after-statement -Wno-pointer-sign -Wno-array-bounds -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -fmacro-prefix-map=./= -Wno-initializer-overrides -Wno-unused-value -Wno-format -Wno-sign-compare -Wno-format-zero-length -Wno-uninitialized -Wno-pointer-to-enum-cast -Wno-unaligned-access -DKBUILD_BASENAME="bounds" -DKBUILD_MODNAME="bounds" -fverbose-asm -S -o kernel/bounds.s kernel/bounds.c

"i"(func01)：例子编译正常但链接报错；"m"(func01)内核编译报错 error: invalid lvalue ... 'm'

"i"(func01) ： 例子 编译正常 但链接为可执行程序则报错；"m"(func01) 内核编译报错 kernel/bounds.c:22:142: error: invalid lvalue in asm input for constraint 'm'